### ISSUE TITLE
Old httpoison dependency

### ISSUE THREAD

**Issue by drozzy** [commanded/commanded-extreme-adapter#14]
Getting this error:

```
Failed to use "httpoison" (versions 1.2.0 and 1.3.0) because
  commanded_extreme_adapter (version 0.5.0) requires ~> 0.11.1
  extreme (versions 0.13.1 and 0.13.2) requires ~> 1.2
```

**Comment by drozzy** [comment]
Just getting weird errors :(

```
could not compile dependency :commanded_extreme_adapter, "mix compile" failed. You can recompile this dependency with "mix deps.compile commanded_extreme_adapter", update it with "mix deps.update commanded_extreme_adapter" or clean it with "mix deps.clean commanded_extreme_adapter"
```

**Comment by slashdotdash** [comment]
Could do with upgrading the `extreme` dependency to the latest version (v0.13.2) and check any other outdated dependencies.

**Comment by drozzy** [comment]
How much can I change :)? 

Are you against me blatantly copying piece of this adapter into a new library(I don’t need the docker stuff or many of the subscribe all functions). Or would you rather I push here?

One thing I’m not a fan of is rather complex name. I was thinking something shorter.
